### ISSUE TITLE
Not all tag images show up

### ISSUE THREAD

**Issue by scottnm** [jmsanchez86/idb#156]
Here's a list of names I've found that fail (i believe because they are just inconsistent with what we are hosting):

- [ ] Corn.png
- [ ] Egg.png
- [ ] Dairy.png
- [ ] Cage.png
- [ ] Gluten.png
- [ ] Finger.png
- [ ] Grass.png
- [ ] Grain.png
- [ ] Lactose.png
- [ ] Hormone.png
- [ ] Nut.png
- [ ] Non.png
- [ ] MSG.png
- [ ] Middle.png
- [ ] No_added.png
- [ ] No_artificial.png
- [ ] Pasture.png
- [ ] Peanut.png
- [ ] Sauce.png
- [ ] Soy.png
- [ ] Sugar.png
- [ ] Sulfite.png
- [ ] Wild.png
- [ ] Wheat.png
- [ ] Sustainable.png
- [ ] Very_healthy.png
- [ ] Vegetarian.png

**Comment by ndbenzinger** [comment]
All broken images should now fixed except for two: Vegetarian because the image name in the folder is lower-case "vegetarian.png" (I can just update the database url to match that if need be) and Sauce which is not there at all from what I can see.

**Comment by scottnm** [comment]
can't we just update the image name in the static folder? and I'll reach out to thomas about getting the sauce image made

**Comment by thomascardwell7** [comment]
Yeah I would update the name. Sorry if I messed that one up. I'll check on the sauce image and make one if I didn't.

**Comment by thomascardwell7** [comment]
Pushed image
