### ISSUE TITLE
Grocery item detail pages don't load

### ISSUE THREAD

**Issue by scottnm** [jmsanchez86/idb#159]
failure from console here

![screen shot 2017-04-06 at 11 15 21 am](https://cloud.githubusercontent.com/assets/5483270/24764587/6f0d1c04-1aba-11e7-8053-db42ebdefbc4.png)

**Comment by jmsanchez86** [comment]
Looks like this refers to an old version, most recent dev branch has no 'id' on line 57.

**Comment by thomascardwell7** [comment]
Did anyone do the npm run pro? That's my bad. I forgot to do that to have the new copy of the minified js.

**Comment by scottnm** [comment]
whoops we can double check and do a new npm run pro
