### ISSUE TITLE
create UML diagrams of models

### ISSUE THREAD

**Issue by scottnm** [jmsanchez86/idb#49]

**Comment by ndbenzinger** [comment]
https://www.draw.io/#G0B6h_quIiiux3YUNFYkVIRkNjbVE

**Comment by ndbenzinger** [comment]
Woops, just noticed we have to use [yUML](https://yuml.me/).

**Comment by ndbenzinger** [comment]
https://github.com/jmsanchez86/idb/blob/yuml/diagram.yuml

To see how it works just copy the file's text into [here](https://yuml.me/diagram/plain/class/draw).

**Comment by scottnm** [comment]
filled in TODOs and included Nutrition
